name: Run tests on demand

on:
  workflow_dispatch:
    inputs:
      test_branch:
        description: 'Test branch to run'
        required: true
        default: 'main'
        type: string
      test_env:
        description: 'Environment to run tests against'
        required: true
        default: 'staging'
        type: choice
        options:
          - development
          - staging
          - production
      test_type:
        description: 'Test type'
        required: true
        default: 'smoke-test'
        type: choice
        options:
          - api-test
          - e2e-test
          - visual-test
          - smoke-test
          - regression-test
      workers:
        description: 'Number of parallel workers'
        required: true
        default: 4
        type: string
      slack_channel:
        description: 'Slack channel to send notifications'
        required: true
        default: '#jenkins-tests-prodtest'
        type: string
